### ISSUE TITLE
Authentication via Oauth Token 

### ISSUE THREAD

**Issue by karankotz** [a-schild/nextcloud-java-api#10]
Hi,

Is there a possibility to provide the authentication method via Oauth token? rather than just the username and password?

I was able to test this with the simple file upload and the upload works fine, but can you please update the file upload method that will authenticate via a token (with the external authentication server like keycloak) rather than the password.

If atleast please provide some insights to implement this using this API code?

I have integrated and configured the keycloak  with the nextcloud, and I want to use the same to upload the files programatically,  this API would be very useful if this had the method to authenticate via Oauth token.

Regards 
Karan

**Comment by a-schild** [comment]
I don't use oauth on our clients, but I will gladly accept a patch which implements it

**Comment by torshid** [comment]
Would be great if someone is able to provide an implementation now that [this app](https://github.com/pulsejet/nextcloud-oidc-login) supports bearer token authentication. :)
