### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by Vaibhav1587** [a-schild/nextcloud-java-api#14]
Is there any API for download file from server ? 

Didn't find any in package. 
Do I have to use the curl call with passing username and password ?

**Comment by a-schild** [comment]
See the downloadFile method in class `org.aarboard.nextcloud.api.webdav.Files`

https://github.com/a-schild/nextcloud-java-api/blob/master/src/main/java/org/aarboard/nextcloud/api/webdav/Files.java
