### ISSUE TITLE
Download file from server not working

### ISSUE THREAD

**Issue by Vaibhav1587** [a-schild/nextcloud-java-api#15]
I'm trying to download the file using Files API but keep on getting NullPointerException.

```
Exception in thread "Thread-1" java.lang.NullPointerException
	at org.aarboard.nextcloud.api.webdav.Files.downloadFile(Files.java:130)
	at com.netand.cloud.utility.DownloadFileTask.downloadFile(DownloadFileTask.java:29)
	at com.netand.cloud.utility.DownloadFileTask.run(DownloadFileTask.java:21)
	at java.lang.Thread.run(Unknown Source)
```
However after debug I get to know the `fileExists(remotepath) returns false`

Here is the example values of the Files class,
```
String path = "https://xxx.xxxxxxxx.xxx/xxxxxxx/remote.php/webdav/files/Test.txt";
String remotepath = "files/Test.txt";
```

**Comment by karankotz** [comment]
I believe you are not specifying the remote path properly.

The "files" path what you have specified is the folder in the Nextcloud?

I have the root folder as the Documents, and here is the test call from the main file, where next is an instance.

`next.downloadFile("/Documents/first.txt");`

**Comment by Vaibhav1587** [comment]
Thanks for the reply.

The file is in the root folder where Documents and Photos folders are

I will also try to download the file under some folder.

**Comment by karankotz** [comment]
In that case, can you specify the remotepath only as "/Test.txt" and try.

**Comment by Vaibhav1587** [comment]
Thanks !! It worked. Apparently we don't required `files/` in the path.

You can close the issue.

**Comment by a-schild** [comment]
Thanks for the follow ups
