### ISSUE TITLE
Trouble Sharing Folder

### ISSUE THREAD

**Issue by jwa3003** [a-schild/nextcloud-java-api#21]
Just having some trouble sharing a folder via url. I know I'm doing it wrong but I'm not sure what.

`//First I connect to nextcloud server`
`NextcloudConnector n = new NextcloudConnector(SERVER,HTTPS,PORT,USER_NAME,USER_PASS);`
`//Then I make a folder`
`n.createFolder("/test");`
`//I then make SharePermissions (This is the step where I defiantly feel like I'm going wrong) `
`SharePermissions permissions = new SharePermissions(SingleRight.READ);`
`//Finally I doShare`
`n.doShare("/test", ShareType.PUBLIC_LINK, "2", true, "1234", permissions); `

I'm getting the following error

`Exception in thread "main" org.aarboard.nextcloud.api.exception.NextcloudApiException: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 401 Unauthorized`

The folder is successfully created but not shared. 

Also is there any documentation on this api I can have a read through?

Cheers,

**Comment by jwa3003** [comment]
Ok yeah I'm not sure who user ID "2" is or why I even put user ID "2".... is there a user or group id for public?

Also no, nothing in nextcloud.log

**Comment by tobiasKaminsky** [comment]
Try it with an empty string.

**Comment by jwa3003** [comment]
Still getting the same error with an empty string

This is the full error:

`Exception in thread "main" org.aarboard.nextcloud.api.exception.NextcloudApiException: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 401 Unauthorized`
`at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:40)`
`at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndCheckStatus(NextcloudResponseHelper.java:17)`
	`at org.aarboard.nextcloud.api.filesharing.FilesharingConnector.doShare(FilesharingConnector.java:163)`
	`at org.aarboard.nextcloud.api.NextcloudConnector.doShare(NextcloudConnector.java:620)`
	`at print.driver.tool.NextCloud.main(NextCloud.java:25)`
`Caused by: java.util.concurrent.ExecutionException: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 401 Unauthorized`
	`at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)`
	`at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)`
	`at org.aarboard.nextcloud.api.utils.NextcloudResponseHelper.getAndWrapException(NextcloudResponseHelper.java:38)`
	`... 4 more`
`Caused by: org.aarboard.nextcloud.api.exception.NextcloudApiException: Request failed with 401 Unauthorized`
	`at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.handleResponse(ConnectorCommon.java:183)`
	`at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:162)`
	`at org.aarboard.nextcloud.api.utils.ConnectorCommon$ResponseCallback.completed(ConnectorCommon.java:147)`
	`at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)`
	`at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)`
	`at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)`
	`at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)`
	`at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)`
	`at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)`
	`at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)`
	`at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)`
	`at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)`
	`at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)`
	`at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)`
	`at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)`
	`at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)`
	`at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)`
	`at java.lang.Thread.run(Thread.java:748)`

> `at print.driver.tool.NextCloud.main(NextCloud.java:25)`

This line refers to:

`n.doShare("/test",ShareType.PUBLIC_LINK,"",true,"1234",permissions);`

**Comment by a-schild** [comment]
A 401 means that you are not allowed to do this.
Either your login is wrong, or you are not allowed to share it.
Does it work whe  you do it in the Nextcloud GUI

**Comment by jwa3003** [comment]
Yeah. That's what I keep going back to. Login must be correct because I can create the folder and yes I can share the folder via the Nextcloud GUI.

**Comment by jwa3003** [comment]
Alright I'm getting a 401 Unauthorized error on the following:

createUser()
getUsers()
editUser()
disableUser()
getUser()
enableUser()
createGroup()
getGroups()
addUserToGroup()
getGroupsOfUser()
getMembersOfGroup()
promoteToSubadmin()
getSubadminGroupsOfUser()
getSubadminsOfGroup()
demoteSubadmin()
removeUserFromGroup()
deleteUser() 
deleteGroup()

However, The following work just fine:

createFolder()
getFolders()
folderExists()
deleteFolder()
uploadFile()
fileExists()
removeFile()
listFolderContent()

I am logging in as an administrator and can do everything from the GUI just fine.

**Comment by a-schild** [comment]
Apparently the password "1234" is not accepted by the NC server.

If I change it to "1234-myWebDav", then the share is created OK

**Comment by LBJSCC** [comment]
> Alright I'm getting a 401 Unauthorized error on the following:
> 
> createUser()
> getUsers()
> editUser()
> disableUser()
> getUser()
> enableUser()
> createGroup()
> getGroups()
> addUserToGroup()
> getGroupsOfUser()
> getMembersOfGroup()
> promoteToSubadmin()
> getSubadminGroupsOfUser()
> getSubadminsOfGroup()
> demoteSubadmin()
> removeUserFromGroup()
> deleteUser()
> deleteGroup()
> 
> However, The following work just fine:
> 
> createFolder()
> getFolders()
> folderExists()
> deleteFolder()
> uploadFile()
> fileExists()
> removeFile()
> listFolderContent()
> 
> I am logging in as an administrator and can do everything from the GUI just fine.
Hi,
I met the same situation with you, could you tell me how you solved it?Thank you very much

**Comment by tobiasKaminsky** [comment]
> Apparently the password "1234" is not accepted by the NC server.

@LBJSCC do you have some kind of password check enabled?
You can also try it with an app token.

**Comment by LBJSCC** [comment]
I am very glad to receive your reply,I will try again to check the configuration of my environment.Thank you very much


------------------ 原始邮件 ------------------
发件人: "Tobias Kaminsky"<notifications@github.com>;
发送时间: 2019年4月29日(星期一) 下午3:32
收件人: "a-schild/nextcloud-java-api"<nextcloud-java-api@noreply.github.com>;
抄送: "LBJ青火"<1193887089@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [a-schild/nextcloud-java-api] Trouble Sharing Folder (#21)



 
Apparently the password "1234" is not accepted by the NC server.
  
@LBJSCC do you have some kind of password check enabled?
 You can also try it with an app token.

**Comment by LBJSCC** [comment]
Hi ,
 
I solved the problem,I feel it is caused by the following reasons:
  
 
The version of the code I downloaded is master ,My colleague downloaded a different version.

  
 
There is a built-in method that differs between the two versions.

 
 
In the version I downloaded:

private static String normalizePath(String path) {
    String s = path;
    if (path == null) {
        return null;
    } else {
        int n;
        for(n = 0; n < s.length() && s.charAt(n) == '/'; ++n) {
            ;
        }

        if (n > 1) {
            s = s.substring(n - 1);
        }

        return s;
    }
}  

    
 
In the downloaded version of my colleague:

 
private static String normalizePath(String path, boolean relative) {
    String s = path;
    if (TextUtils.isBlank(path)) {
        return "";
    } else {
        int n;
        for(n = 0; n < s.length() && s.charAt(n) == '/'; ++n) {
            ;
        }

        if (n > 1) {
            s = s.substring(n - 1);
        }

        if (!relative && !s.startsWith("/")) {
            s = "/" + s;
        }

        return s;
    }
}
I guess it is because the two methods are different. Can you verify the same,
Thank you very much;
 

 ------------------ 原始邮件 ------------------
  发件人: "Tobias Kaminsky"<notifications@github.com>;
 发送时间: 2019年4月29日(星期一) 下午3:32
 收件人: "a-schild/nextcloud-java-api"<nextcloud-java-api@noreply.github.com>;
 抄送: "LBJ青火"<1193887089@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [a-schild/nextcloud-java-api] Trouble Sharing Folder (#21)

 

  
Apparently the password "1234" is not accepted by the NC server.
 
@LBJSCC do you have some kind of password check enabled?
You can also try it with an app token.

**Comment by a-schild** [comment]
Where have you gotten that code from?
Is it part of this repository, if yes, what class?

**Comment by tobiasKaminsky** [comment]
A quick scan reveals that there is no normalizePath in this repo.

**Comment by LBJSCC** [comment]
I also downloaded the code on the main branch(https://github.com/a-schild/nextcloud-java-api.git)

  
 
The version of the code I downloaded added this dependency to pom.xml:
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5</version>
</dependency>
 
 
The different method name is normalizePath, which is in URIBuilder class



  (/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.jar!/org/apache/http/client/utils/URIBuilder.class:20)
  
   
 
If you need me, I can send you the source ZIP package I downloaded.


 
Thank you for your answer
 

 ------------------ 原始邮件 ------------------
  发件人: "André Schild"<notifications@github.com>;
 发送时间: 2019年5月10日(星期五) 晚上7:31
 收件人: "a-schild/nextcloud-java-api"<nextcloud-java-api@noreply.github.com>;
 抄送: "LBJ青火"<1193887089@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [a-schild/nextcloud-java-api] Trouble Sharing Folder (#21)

 

 
Where have you gotten that code from?
Is it part of this repository, if yes, what class?

**Comment by a-schild** [comment]
Do you know which version of the httpclient package is working, and which does not?
So we can check it and look into the dependencies

**Comment by LBJSCC** [comment]
The correct code on my side is httpclient with version 4.5.6,
the other is the 4.5 version of httpclinet.
  
 The reason for this problem in my environment is that I have specified version 4.5. I'm really sorry for the trouble caused to you  

 ------------------ 原始邮件 ------------------
  发件人: "André Schild"<notifications@github.com>;
 发送时间: 2019年5月11日(星期六) 中午1:57
 收件人: "a-schild/nextcloud-java-api"<nextcloud-java-api@noreply.github.com>;
 抄送: "LBJ青火"<1193887089@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [a-schild/nextcloud-java-api] Trouble Sharing Folder (#21)

 

 
Do you know which version of the httpclient package is working, and which does not?
So we can check it and look into the dependencies
