### ISSUE TITLE
add ShareType email

### ISSUE THREAD

**Issue by mirkomack** [a-schild/nextcloud-java-api#23]
I need the option to create a share with an email. The newest version of Nextcloud will send a notification to the provided email address after a share of the type EMAIL (enum value 4) has been created.

**Comment by mirkomack** [comment]
I created a pull request after testing this against a Nextcloud 14.0.4 installation

**Comment by mirkomack** [comment]
example usage:
`connector.doShare("/myfile.png", ShareType.EMAIL, "theuser@example.com", false, null, new SharePermissions(SharePermissions.SingleRight.READ));`

**Comment by a-schild** [comment]
Is implemented in 11.0.3,
thanks for your help
