### ISSUE TITLE
[Feature Request] Getting the InputStream of a remote file

### ISSUE THREAD

**Issue by SimonIT** [a-schild/nextcloud-java-api#27]
Thanks for this nice lib.
It would be really great if there was a method for getting the InputStream of a remote file. I wanna directly process the retrieved file. Writing and then again reading from the hard drive are making the processing slower.

**Comment by a-schild** [comment]
??? I don't understand what you mean...

jave supports processing of remote files.
The processed files are then stored locally.

If you wish to first process the remote file, then you can create an inputstream by normal java ways.

Or do you wish to receive the output of the transcoded file as an InputStream in your application?

**Comment by SimonIT** [comment]
I wanna get directly the inputstream from the webdav.
The writing to the hard drive in `downloadFile` is for me unnecessary because I wanna process directly the file.
Currently I can only read the file from the hard drive which would be unnecessary if can get directly the inputstream.

**Comment by a-schild** [comment]
@SimonIT Sorry, I mixed up with another github project.
Now it's clear what you mean

**Comment by SimonIT** [comment]
I think a byte[] would also be fine, if it's not possible to get the inputstream

**Comment by a-schild** [comment]
Can you please try with the 11.1.0-SNAPSHOT release?

It has a new `dowloadFile` method with this signature:

 `public InputStream downloadFile(String remotepath) throws IOException`

Returning a `byte[]` is potentially a bad idea, when the downloaded files are huge.
With the `InputStream` you can do this yourself if needed.

**Comment by SimonIT** [comment]
Works, thanks for implementing

**Comment by tobiasKaminsky** [comment]
@SimonIT just remember to close the stream after usage :-)
