### ISSUE TITLE
Support for application configuration API

### ISSUE THREAD

**Issue by col-panic** [a-schild/nextcloud-java-api#33]
The nextcloud API supports application configuration (see e.g. https://github.com/nextcloud/server/issues/10961 and the respective controller interface https://github.com/nextcloud/server/blob/master/apps/provisioning_api/lib/Controller/AppConfigController.php).

Support for this should be included in nextcloud-java-api.

I am working on a PR for this.

**Comment by a-schild** [comment]
A merge request would be integrated... ;)

**Comment by col-panic** [comment]
I created a draft pull request for my current state - so you can have a first view! Tests are yet missing.

**Comment by a-schild** [comment]
Thanks for the enhancements
