### ISSUE TITLE
How can i get the urls of the files

### ISSUE THREAD

**Issue by YiwenCabbage** [a-schild/nextcloud-java-api#37]
I'd tried the method "doShare" but i'd got the error 401.

Code like below:
SharePermissions permissions = new SharePermissions(SingleRight.READ);
FilesharingConnector instance=new FilesharingConnector(this.getSever());
Share result=instance.doShare("testing",ShareType.EMAIL,"xxx@outlook.com", null,null,null);

And i found the issus which had this same problem, i changed the depenency "hettpClient" to the version 4.5.6 but it still dosen't work. But the method like uploadfile and creatfolder are working well.

I'm not sure if "doShare" can get the urls of the files. If not, do we have any other method to realise it?
Thank you for your   ##attention.

**Comment by a-schild** [comment]
Error 401 means that you don't have the rights or that the authentication is missing/wrong.
Can you share the resource in the webinterface when using the same login as in the code?

**Comment by a-schild** [comment]
Have you looked at this example/test code?

https://github.com/a-schild/nextcloud-java-api/blob/master/src/test/java/org/aarboard/nextcloud/api/filesharing/FilesharingConnectorTest.java

**Comment by YiwenCabbage** [comment]
Yes i'd read it. And the main part of my code is like:

```
         NextcloudConnector iotConnect;
         String url = "https://xxx.fr/remote.php/webdav";
         String username = "iotready";
        String password = "xxx";
         ServerConfig _serverConfig;
        iotConnect = new NextcloudConnector(url, username, password);
        URL _serviceUrl = new URL(url);
        _serverConfig = new ServerConfig(_serviceUrl.getHost(), true, _serviceUrl.getPort(), username, password);
        SharePermissions permissions = new SharePermissions(SingleRight.READ);
        FilesharingConnector instance=new FilesharingConnector(_serverConfig);
        Share result=instance.doShare("testing", ShareType.EMAIL,"cabbage1601@outlook.com", true,"1234-myWebDav",permissions);
        assertNotNull(result);
```
I'd also tried the "upLoadFile" and 'creatFolder' in the same time ,they worked well.
Thank you  for helping.
