### ISSUE TITLE
Working with downloaded InputStream fails 

### ISSUE THREAD

**Issue by jonybuzz** [a-schild/nextcloud-java-api#46]
version: 11.3.0
java: 1.8

I used method `InputStream downloadFile(String remotepath)` and when I try to read all bytes from that stream, it throws
`java.net.SocketException: socket closed`

I believe the problem is where sardine is shutdown after the download

**Comment by a-schild** [comment]
Do you have a more complete example?
And how large is the dowloaded URL over which connection?

**Comment by jonybuzz** [comment]
Preparing a sample project...

**Comment by micrus009** [comment]
below is an example:

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import org.aarboard.nextcloud.api.NextcloudConnector;
import org.aarboard.nextcloud.api.webdav.ResourceProperties;
import org.apache.commons.io.FileUtils;

public class NextCloudApiTest {

	public static void main(String[] args) throws IOException 
	{
		NextcloudConnector connect = new NextcloudConnector("https://kmu.files.cnow.at", "XXXXXXXXXXXX", "YYYYYYYYYYYYY");
		System.out.println(connect.folderExists("/sardine"));
		List<String> listFolderContent = connect.listFolderContent("/sardine", -1, false, true);
		for (String element : listFolderContent) 
		{
			ResourceProperties properties = connect.getProperties("/" + element, true);
			System.out.println(element + ", " + properties.getContentLength());
		}

		connect.uploadFile(new File("C:/FOLDER/MioReport.pdf"), "/sardine/Report2.pdf");
		InputStream inputStream = connect.downloadFile("/sardine/Report2.pdf");
		FileUtils.copyInputStreamToFile(inputStream, new File("C:/FOLDER/DownloadMioReport2.pdf"));
		inputStream.close();
		connect.shutdown();
	}
}



SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
true
sardine/, -1
sardine/Prova/, -1
sardine/Prova/aaa/, -1
sardine/Report.pdf, 74137
sardine/Report2.pdf, 74137
gen 14, 2021 2:25:51 PM com.github.sardine.impl.io.HttpMethodReleaseInputStream close
AVVERTENZA: Abort connection for response HttpResponseProxy{HTTP/1.1 200 OK [Cache-Control: no-store, no-cache, must-revalidate, Content-Disposition: attachment; filename*=UTF-8''Report2.pdf; filename="Report2.pdf", Content-Length: 74137, Content-Security-Policy: default-src 'none';, Content-Type: application/pdf, Date: Thu, 14 Jan 2021 13:23:07 GMT, Etag: "983b36febabf65b71de01019d774e60e", Expires: Thu, 19 Nov 1981 08:52:00 GMT, Last-Modified: Thu, 14 Jan 2021 13:25:50 GMT, Oc-Etag: "983b36febabf65b71de01019d774e60e", Pragma: no-cache, Referrer-Policy: no-referrer, Server: Apache/2.4.25 (Debian), Set-Cookie: ocpkp0451vng=f3e91187e57ca9699061bf83f884f128; path=/; secure; HttpOnly, Set-Cookie: oc_sessionPassphrase=O%2ByUYWdZtyHLJlq3iuumyMZaF3zSETDjOZNVfGcvP6XMO2pmLHGdxQluWORouthqlkQgJzi2XR0tpyurHjC%2FNcvj%2FaVecBqM5DIKwgbvayasdg8JCYjRSlLHRUBZ7%2FZc; path=/; secure; HttpOnly, Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax, Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict, Set-Cookie: ocpkp0451vng=11d6f87545923f36bcf0152c893295fc; path=/; secure; HttpOnly, Set-Cookie: cookie_test=test; expires=Thu, 14-Jan-2021 14:23:07 GMT; Max-Age=3600, Strict-Transport-Security: max-age=15552000; includeSubDomains, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Powered-By: PHP/7.2.14, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block] ResponseEntityProxy{[Content-Type: application/pdf,Content-Length: 74137,Chunked: false]}}
gen 14, 2021 2:25:51 PM com.github.sardine.impl.io.HttpMethodReleaseInputStream close
AVVERTENZA: Abort connection for response HttpResponseProxy{HTTP/1.1 200 OK [Cache-Control: no-store, no-cache, must-revalidate, Content-Disposition: attachment; filename*=UTF-8''Report2.pdf; filename="Report2.pdf", Content-Length: 74137, Content-Security-Policy: default-src 'none';, Content-Type: application/pdf, Date: Thu, 14 Jan 2021 13:23:07 GMT, Etag: "983b36febabf65b71de01019d774e60e", Expires: Thu, 19 Nov 1981 08:52:00 GMT, Last-Modified: Thu, 14 Jan 2021 13:25:50 GMT, Oc-Etag: "983b36febabf65b71de01019d774e60e", Pragma: no-cache, Referrer-Policy: no-referrer, Server: Apache/2.4.25 (Debian), Set-Cookie: ocpkp0451vng=f3e91187e57ca9699061bf83f884f128; path=/; secure; HttpOnly, Set-Cookie: oc_sessionPassphrase=O%2ByUYWdZtyHLJlq3iuumyMZaF3zSETDjOZNVfGcvP6XMO2pmLHGdxQluWORouthqlkQgJzi2XR0tpyurHjC%2FNcvj%2FaVecBqM5DIKwgbvayasdg8JCYjRSlLHRUBZ7%2FZc; path=/; secure; HttpOnly, Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax, Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict, Set-Cookie: ocpkp0451vng=11d6f87545923f36bcf0152c893295fc; path=/; secure; HttpOnly, Set-Cookie: cookie_test=test; expires=Thu, 14-Jan-2021 14:23:07 GMT; Max-Age=3600, Strict-Transport-Security: max-age=15552000; includeSubDomains, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Powered-By: PHP/7.2.14, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block] ResponseEntityProxy{[Content-Type: application/pdf,Content-Length: 74137,Chunked: false]}}
Exception in thread "main" java.net.SocketException: Socket is closed
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1524)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:95)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at com.github.sardine.impl.io.ByteCountInputStream.read(ByteCountInputStream.java:52)
	at com.github.sardine.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:56)
	at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:78)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1530)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1506)
	at nextcloud.api.test.NextCloudApiTest.main(NextCloudApiTest.java:26)
