### ISSUE TITLE
Getting error 405 and error 404

### ISSUE THREAD

**Issue by JonCSgr** [a-schild/nextcloud-java-api#51]
Hello i am trying to use the library but i am lost .
I use
NextcloudConnector nextcloud = new NextcloudConnector("serverIPaddress/nextcloud",false,80,"admin","pass");

Then if i use 
nextcloud.get methods i get error 404

if i use nextcloud.create methods i get error 405.

My nextcloud is installed on apache on ubuntu 20.0.4 .

Any help is appreciated. Thanks.

**Comment by a-schild** [comment]
Look at the open pull request, I think it struggels over the folder in the Server adress.

**Comment by JonCSgr** [comment]
Seems like after i complied it with different values on the serverIpAddress it fixed itself with "10.0.0.0" no "/" or "/nextcloud"

Thanks for offering this library and responding so fast if i have any issues i will let you know :)
