### ISSUE TITLE
If i want to give a user permissions edit,create,reshare but not delete , is this possible?

### ISSUE THREAD

**Issue by JonCSgr** [a-schild/nextcloud-java-api#53]
Hey again, and happy x-mas . 
i have a questions.

If i want to give a user permissions edit,create,reshare but not delete , is this possible?

Also i made some functions like remove all shares from a specific user , how can i contribute to you ?

**Comment by JonCSgr** [comment]
Can this be done?

**Comment by a-schild** [comment]
Why should this not be possible?
If Nextcloud can do it, then via API this is also possible.

https://help.nextcloud.com/t/how-can-i-disable-delete-for-users-of-a-share/8391/24

I think you can only remove the delete right on shares to users and not to "shares via link"

For the second question, just fork it on github and the submit a merge request with your changes

**Comment by JonCSgr** [comment]
i meant with your library,  you have 31 = all permissions (edit,create,reshare,delete) and 1 for read only() and some others only for create or only for share.

What if i want to use only edit,create,reshare but not delete , can ur library achieve this ?

**Comment by a-schild** [comment]
You can add the rights with  passing multiple rights here.

`public SharePermissions(SingleRight... permissions) `

**Comment by JonCSgr** [comment]
> You can add the rights with passing multiple rights here.
> 
> `public SharePermissions(SingleRight... permissions) `

Thank you so much :)
