### ISSUE TITLE
API method to download a file?

### ISSUE THREAD

**Issue by sachinkariyattin** [a-schild/nextcloud-java-api#9]
Hello, 

Nice work. But I dont see a method to download a file from the server. Would be great if that can be added. Do you still plan to work on this?

or please let me know how to get started and I will be happy to contribute

**Comment by a-schild** [comment]
The api was primarly designed to manage the nextcloud.
The file related operations are usually done via some webdav library

**Comment by karankotz** [comment]
@a-schild I am working on writing the download file, folder methods will soon send a PR.

**Comment by tobiasKaminsky** [comment]
@karankotz you can have also a look at https://github.com/nextcloud/android-library.
Though is is specific for Android, you can maybe get inspired by it, as both is java.

**Comment by karankotz** [comment]
@a-schild @sachinkariyattin I have added the methods to download the file and download the folder.
Please review the same.

**Comment by karankotz** [comment]
@tobiasKaminsky Thanks! I checked the repo looks great!, I would take it's help while writing the upload folder method.

**Comment by tobiasKaminsky** [comment]
As I am one of the devs from android app/library, feel free to ask, if you need any advice.

**Comment by a-schild** [comment]
Has just been added with pull request #11 
Thanks

**Comment by karankotz** [comment]
@tobiasKaminsky Thanks, I would surely ask you for any help!

**Comment by karankotz** [comment]
@tobiasKaminsky Is there a way to contact you via email? I am working on Nextcloud server and need some help on the authentication and authorization of the external user base, please update me on the same, as it would be fairly a good chance to seek your inputs.

**Comment by tobiasKaminsky** [comment]
tobias at nextcloud dot com, while I prefer to discuss everything in public, so that everyone can participate and help.

**Comment by karankotz** [comment]
Thanks! I will point you out via your email by raising a support request at the nextcloud community.

**Comment by tobiasKaminsky** [comment]
Can you link the issue here (I am not that active on NC discourse, so I might miss it)
